@extends('layouts.dashboard')
@section('styles')
@include('shared.chat-css')
@endsection
@section('content')
@include('shared.chat')
@endsection
@section('javascript')
@include('shared.chat-js')
@endsection